apiVersion: v1
kind: Service
metadata:
  name: tracksphere-frontend
  labels:
    app: tracksphere-frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: tracksphere-frontend
